parameters:
  # TODO : Back admin
  admin.url: "https://localhost:8000/admin"
  admin.name: "Admin"

  # TODO : Back charts
  charts.url: "https://localhost:8000/admin/charts"
  charts.name: "Dashboard"

  # TODO : Back charts pie
  piecharts.url: "https://localhost:8000/admin/charts/pie"
  piecharts.name: "Pie charts"
# test
